Class Large.BenchmarkClass Extends %RegisteredObject
{

ClassMethod Method00(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method01(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method02(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method03(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method04(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method05(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method06(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method07(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method08(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method09(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method10(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method11(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method12(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method13(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method14(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method15(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method16(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method17(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method18(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method19(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method20(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method21(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method22(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method23(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method24(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method25(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method26(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method27(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method28(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method29(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method30(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method31(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method32(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method33(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method34(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method35(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method36(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method37(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method38(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method39(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method40(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method41(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method42(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method43(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method44(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method45(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method46(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method47(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method48(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method49(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method50(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method51(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method52(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method53(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method54(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method55(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method56(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method57(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method58(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method59(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method60(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method61(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method62(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method63(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method64(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method65(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method66(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method67(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method68(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method69(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method70(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method71(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method72(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method73(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method74(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method75(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method76(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method77(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method78(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

ClassMethod Method79(arg1 As %String, arg2 As %Integer, arg3 As %Boolean, arg4 As %Float) As %Boolean
{
    Set tVal0 = arg2 + 0
    Set tVal1 = arg2 + 1
    Set tVal2 = arg2 + 2
    Quit (arg2 > 0)
}

}
